trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "This is a sample text file." > sample.txt
  displayName: 'Create sample text file'

- publish: "sample.txt"
  artifact: "sample"