trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "This is a sample artifact file." > artifact.txt
  displayName: 'Create Artifact File'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
