trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: PrintJob
    steps:
    - template: template.yaml  # Reference the template
      parameters:
        message: 'Hello from template!'  # Pass a value to the template parameter
