# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: NAveen
    jobs:
    - job: testjob1
      displayName: testjob
      steps:
      - script: |
                echo test
                touch test_touch.txt
                ls
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/test_touch.txt
          artifact: touch

    - job: testjob2
      displayName: testjob2
      steps:
        - script: |
                  echo test in job 2
                  ls
        - task: DownloadPipelineArtifact@2
          inputs:
           artifactName: touch
        
        - script: |
                  echo test in job2 for second time
                  ls


    