# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: NAveen
    jobs:
    - job: testjob1
      displayName: testjob
      steps:
      - script: |
                echo test
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"

    - job: testjob2
      displayName: testjob2
      steps:
        - script: |
                  echo test in job 2


    