on: pull_request
name: Main Workflow
jobs:
  artifactoryUpload:
    name: Upload Trigger
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: build
      run: test.bat
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://gfx-assets.sh.intel.com/'
        credentials type: 'apikey'
        apikey: ${{ secrets.RT_APIKEY }}
        args: u "dist/*" "/mu/repo/path/" --recursive=true --build-name=myawesomeapp
