# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  pull_request:
  
jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step 0 -> test the local dir
        run: dir

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          dir
          cd downloads
          echo 'alpha1'    > alpha.html
          echo 'bravo2'    > bravo.html
          echo 'charlie3'  > charlie.html
          cd ..
          cp test.py downloads
          dir
          pwd
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads

      - name: Step 4 - Use the Upload Artifact GitHub Action
        uses: actions/download-artifact@v2
        with:
          name: assets-for-download
          path: /home/      
